# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_miniblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加日期')),
                ('mod_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改日期')),
                ('content', models.TextField(max_length=2000, verbose_name='内容')),
            ],
        ),
    ]
