# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_miniblog', '0002_item_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='post',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mod_date',
        ),
    ]
