# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=2000)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('mod_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
